[package]
name = "dusk-ui-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
dusk-app = { path = "../app" }
dusk-domain = { path = "../domain" }

[dev-dependencies]
dusk-ddc-fake = { path = "../ddc-fake" }

[lints]
workspace = true
