[package]
name = "dusk-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
dusk-domain = { path = "../domain" }
dusk-ipc = { path = "../ipc" }
serde_json = "1"

[dev-dependencies]
dusk-app = { path = "../app" }
dusk-ddc-fake = { path = "../ddc-fake" }

[lints]
workspace = true
