//! Dusk's icons. They are embedded in duskd.exe (crates/bin-daemon/duskd.rc)
//! and generated by assets/icons/make_icons.py. Without the resources (e.g.
//! in tests) the generic application icon is used.

use std::ffi::c_void;

use windows::Win32::Foundation::HINSTANCE;
use windows::Win32::System::LibraryLoader::GetModuleHandleW;
use windows::Win32::System::Registry::{HKEY_CURRENT_USER, RRF_RT_REG_DWORD, RegGetValueW};
use windows::Win32::UI::WindowsAndMessaging::{
    GetSystemMetrics, HICON, IDI_APPLICATION, IMAGE_ICON, LR_SHARED, LoadIconW, LoadImageW,
    SM_CXICON, SM_CXSMICON,
};
use windows::core::{PCWSTR, w};

/// Resource IDs in duskd.rc.
const APP_ICON: u16 = 1;
/// White glyph, for dark taskbars.
const TRAY_FOR_DARK_TASKBAR: u16 = 101;
/// Black glyph, for light taskbars.
const TRAY_FOR_LIGHT_TASKBAR: u16 = 102;

/// The tray glyph that contrasts with the taskbar.
pub(crate) fn tray_icon_id(light_taskbar: bool) -> u16 {
    if light_taskbar {
        TRAY_FOR_LIGHT_TASKBAR
    } else {
        TRAY_FOR_DARK_TASKBAR
    }
}

/// The taskbar follows the Windows mode ("SystemUsesLightTheme"), which can
/// differ from the app mode the Settings window follows.
pub(crate) fn taskbar_is_light() -> bool {
    let mut data: u32 = 0;
    let mut size = size_of::<u32>() as u32;
    let result = unsafe {
        RegGetValueW(
            HKEY_CURRENT_USER,
            w!("Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize"),
            w!("SystemUsesLightTheme"),
            RRF_RT_REG_DWORD,
            None,
            Some((&mut data as *mut u32).cast::<c_void>()),
            Some(&mut size),
        )
    };
    result.is_ok() && data == 1
}

fn load(id: u16, size: i32) -> HICON {
    let loaded = unsafe {
        let module = GetModuleHandleW(None).unwrap_or_default();
        LoadImageW(
            Some(HINSTANCE(module.0)),
            // MAKEINTRESOURCE: an integer resource ID in place of a name.
            PCWSTR(id as usize as *const u16),
            IMAGE_ICON,
            size,
            size,
            LR_SHARED,
        )
    };
    match loaded {
        Ok(handle) if !handle.is_invalid() => HICON(handle.0),
        _ => unsafe { LoadIconW(None, IDI_APPLICATION) }.unwrap_or_default(),
    }
}

/// The tray icon for the current taskbar theme, at the system's small-icon size.
pub(crate) fn tray() -> HICON {
    load(tray_icon_id(taskbar_is_light()), unsafe {
        GetSystemMetrics(SM_CXSMICON)
    })
}

/// The app icon at the large (Alt-Tab) and small (title bar) sizes.
pub(crate) fn app_icons() -> (HICON, HICON) {
    unsafe {
        (
            load(APP_ICON, GetSystemMetrics(SM_CXICON)),
            load(APP_ICON, GetSystemMetrics(SM_CXSMICON)),
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_tray_glyph_contrasts_with_the_taskbar() {
        assert_eq!(tray_icon_id(true), TRAY_FOR_LIGHT_TASKBAR);
        assert_eq!(tray_icon_id(false), TRAY_FOR_DARK_TASKBAR);
    }

    #[test]
    fn missing_resources_fall_back_to_a_usable_icon() {
        // Test executables carry no icon resources.
        assert!(!tray().is_invalid());
        let (large, small) = app_icons();
        assert!(!large.is_invalid() && !small.is_invalid());
    }
}
