[package]
name = "dusk-store-file"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
log = "0.4"
dusk-app = { path = "../app" }
dusk-domain = { path = "../domain" }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
windows = { version = "0.62", features = ["Win32_Storage_FileSystem"] }

[lints]
workspace = true
