[package]
name = "dusk-store-file"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
log = "0.4"
dusk-app = { path = "../app" }
dusk-domain = { path = "../domain" }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
windows = { version = "0.62", features = ["Win32_Storage_FileSystem"] }
